version: '3.9'

networks:
  distance:
volumes:
  distance-db:

services:
  db:
    image: postgres:16-alpine
    container_name: distance-db
    environment:
      - TZ=Asia/Yangon
      - POSTGRES_USER=distance
      - POSTGRES_PASSWORD=distance
      - POSTGRES_DB=distance
      - POSTGRESQL_MAX_CONNECTIONS=200
    networks:
      - distance
    ports:
      - 5432:5432
    volumes:
      - distance-db:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
