networks:
  converters:
volumes:
  database:

services:
  db:
    image: postgres:alpine
    container_name: testdb
    environment:
      - TZ=Asia/Yangon
      - POSTGRES_USER=testdb
      - POSTGRES_PASSWORD=testdb
      - POSTGRES_DB=testdb
    networks:
      - converters
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data
