create table division (
    id integer generated by default as identity,
    capital varchar(255),
    name varchar(255),
    region varchar(255),
    primary key (id)
);

insert into division (name, capital, region) values ('Ayeyarwady Region', 'Pathein', 'South');
insert into division (name, capital, region) values ('Ayeyarwady Region', 'Pathein', 'South');
insert into division (name, capital, region) values ('Ayeyarwady Region', 'Pathein', 'South');
insert into division (name, capital, region) values ('Ayeyarwady Region', 'Pathein', 'South');
insert into division (name, capital, region) values ('Ayeyarwady Region', 'Pathein', 'South');
insert into division (name, capital, region) values ('Ayeyarwady Region', 'Pathein', 'South');
insert into division (name, capital, region) values ('Ayeyarwady Region', 'Pathein', 'South');
insert into division (name, capital, region) values ('Ayeyarwady Region', 'Pathein', 'South');
insert into division (name, capital, region) values ('Ayeyarwady Region', 'Pathein', 'South');
insert into division (name, capital, region) values ('Ayeyarwady Region', 'Pathein', 'South');
insert into division (name, capital, region) values ('Ayeyarwady Region', 'Pathein', 'South');
insert into division (name, capital, region) values ('Ayeyarwady Region', 'Pathein', 'South');
insert into division (name, capital, region) values ('Ayeyarwady Region', 'Pathein', 'South');
insert into division (name, capital, region) values ('Ayeyarwady Region', 'Pathein', 'South');
insert into division (name, capital, region) values ('Ayeyarwady Region', 'Pathein', 'South');